# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IfIpPvt8mm4QlLUwtKEH87JpWAAA2ili
"""

import matplotlib.pyplot as plt

hours = [1, 2, 3, 4, 5, 6, 7, 8]
visitors = [50, 45, 60 , 90, 120, 140, 150, 130]

plt.plot(hours,visitors,
         color = 'blue',
         marker = "s",
         linestyle= "--",
         linewidth=2,
         alpha=1,
         label="Visitors")
plt.title("Website Visitors Per Hour")
plt.xlabel("Hour of Day")
plt.ylabel("Number of Visitors")
plt.legend()

plt.grid(True,linestyle="-", alpha=1)
plt.show()

import matplotlib.pyplot as plt
products = ["Laptop","Mobile","Tablet","Headphones","Smartwatch"]
sales = [150, 200, 180, 80, 100]

plt.bar(products, sales, color="Blue", edgecolor="orange",alpha=1,width=0.5)
plt.title("Products Sales Comparsion")
plt.xlabel("Products")
plt.ylabel("units Sold")
plt.show()

marks = [45, 55, 65, 60, 72, 67, 89, 90, 27, 89,
         45, 67, 54, 65, 91, 100, 20, 87, 90,80,
         80, 85, 95, 80 ,94,50, 70, 75, 80, 60]

plt.hist(marks, bins=3, histtype='bar', color = 'green', edgecolor='pink',density=False)
plt.title("Distribution of Student Marks")
plt.xlabel("Marks Range")
plt.ylabel("Number of Students")
plt.show()

brand = ["Apple", "Samsung", "Xiaomi","Oppo","others"]
market_share = [33, 20, 10,17, 20]
plt.pie(market_share ,
        labels = brand,
        autopct = "%.2f%%",
        startangle = 90,
        colors = ['blue', 'green', 'yellow', 'orange','purple'],
        explode = [0,0,0,0.2,0],
        shadow = True)
plt.title("Mobile Market Share 2025")
plt.show()

import matplotlib.pyplot as pit
ad_spend = [2, 4, 5, 6, 1, 7, 6, 7, 8, 9]
sales = [23, 56, 45, 34, 23,45,56,76,54,32,]
profit =  [ 200, 150, 201, 189, 160, 90,175, 120, 40,100]
colors = [8, 3, 2,9, 4,9, 3,8,3,1]

plt.scatter(ad_spend, sales,
            s = profit,
            c = colors,
            cmap ="Reds",
            alpha = 0.2,
            edgecolors='black',
            linewidths=1.2)
plt.title("Advertising Spend Vs Sales (with Color & Size)",fontsize=14, fontweight = 'bold')
plt.xlabel("Ad Spend ($10000)",fontsize=12)
plt.ylabel("Sales ($10000)", fontsize=12)

plt.colorbar(label="Slaes Value")
plt.grid(True, linestyle="--",alpha=0.4)
plt.show()

import matplotlib.pyplot as plt
scores=[[60,65,70,80,2],
        [70,74,80,90,95],
        [35,40,43,54,55],
        [15,20,17,29,95],
        [56,65,64,59,70]
]
plt.boxplot(scores,
            patch_artist=True,
            medianprops=dict(color="green",linewidth=1),
            whiskerprops=dict(color="pink",linewidth=1),
            capprops=dict(color="yellow",linewidth=1),
            notch=False,
            vert=True,
            labels=["A","B","C","D","E"])
plt.title("Exam Score Distribution Across Classes")
plt.xlabel("Classes")
plt.ylabel("Scores")
plt.grid(True,linestyle="--",alpha=0.5)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
data=np.array([
    [30,25,35,40,65],
    [33,30,29,27,25],
    [36,32,40,45,23],
    [45,67,98,90,67]
])
days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
weeks=["Week1","Week2","Week3","Week4"]
sns.heatmap(data,
            annot=True,
            fmt=".2f",
            cmap="YlOrRd",
            linewidth=1,
            xticklabels=days,
            yticklabels=weeks)
plt.title("Weekly Temperature Heatmap",fontsize=14,fontweight="bold")
plt.xlabel("Days of the Week")
plt.ylabel("Weeks")
plt.show()