# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEscN0ZexnfC_pW78WJZoNc3ryE47tdu
"""

import pandas as pd
prices=[299,450,320,610,200]
products=["earbuds",'Mobile Pouch','smartwatch','bluetoot','glass']
pp= pd.Series(prices,index=products)
print(pp)

print("Mean:",pp.mean())
print("Sum:",pp.sum())
print("Max:",pp.max())
print("Min:",pp.min())

print(pp.head(3))
print(pp.tail(2))

print(pp.apply(lambda x: f'{x+(x*0.18)}'))
print(pp.map(lambda x: f"{x}.00"))

print(pp.sort_values())
print(pp.sort_index())
print(pp.sort_index(ascending = False))
print(pp.value_counts())

import pandas as pd
data = {
    "Products": ["Earbuds","smartphone","laptop","Smartwatch","Bluetooth"],
    "Brand": ["Soundmax","Samsang","Acer","Noise","Boat"],
    "Price": [299,16000,54000,2000,1500],
    "Stock": [50,30,25,90,48],
    "Bestseller": [True, False, True, False, False]
}
df = pd.DataFrame(data)
print(df)

from google.colab import files
import pandas as pd

uploaded  = files.upload()
df = pd.read_excel("products_50_rows.xlsx")
print(df)

print(df.shape)
print(df.columns)
print(df.info())

print(df.head(5))
print(df.tail(5))

print(df.iloc[0])
print(df.iloc[1])

print(df["Product"])

print(df)
print(df.loc[2, "Brand"])
print(df.loc[3, "Product"])
print(df.loc[12, "Stock"])

print(df.iloc[4, 0])
print(df.iloc[2, 1])
print(df.iloc[3, 3])

df_dropped = df.drop(columns=["Stock"])
#df.drop(columns=["stock"],inplace=True)
print(df_dropped)

df_renamed = df.rename(columns={"Price": "Cost"})
print(df_renamed)
#df.rename(columns={"Product": "Product Name"},input=True)

print(df)
print(df.loc[df["BestSeller"]==True])
print(df.loc[df["Stock"]<40])
print(df.loc[df["Price"]<10000])

df_grouped = df.groupby("Brand").agg({"Price": "mean", "Stock": "sum"})
print(df_grouped)

grouped = df.groupby("Brand").agg({"Price":["mean", "max", "min", "sum"]})
print(grouped)

grouped = df.groupby("Brand")["Price"].mean()
print(grouped)

data2 = {
    "Brand": ["SoundMax","TechNova","Bytecore","TimeTrack","EchoBoom"],
    "Rating": [4.2,3.0,4.7,3.9,4.0],
    "Discount": [28,40,16,20,5]
}
df_ratings = pd.DataFrame(data2)
print(df_ratings)

df_merged = df.merge(df_ratings, on = "Brand")
print("Merged DataFrame (Adding Rating):\n", df_merged)

new_data ={
    "Product": ["Tablet"],
    "Brand": ["Smartware"],
    "price": [12999],
    "Stock": [25],
    "BestSeller": [True]
}
df_new = pd.DataFrame(new_data)
print(df_new)

df_concat = pd.concat([df, df_new], ignore_index = True)
print("Concatenated DataFrame:\n",df_concat)